[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800

lib_deps =
  h2zero/NimBLE-Arduino @ ^2.3.6
  bodmer/TFT_eSPI @ ^2.5.43

build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  ; 明确指定 ST7789 320x170，避免依赖库默认 User_Setup
  -DUSER_SETUP_LOADED=1
  -DST7789_DRIVER
  -DTFT_WIDTH=320
  -DTFT_HEIGHT=170
  -DTFT_MOSI=7
  -DTFT_SCLK=6
  -DTFT_CS=3
  -DTFT_DC=2
  -DTFT_RST=10
