[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
  h2zero/NimBLE-Arduino @ ^2.3.6
  bodmer/TFT_eSPI @ ^2.5.43
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
